"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowser } from "@/lib/supabase-browser";
import { EmptyProfile } from "@/lib/schema";
import majors from "@/data/majors.json";
import schools from "@/data/schools.json";
import roundRules from "@/data/rounds.json";
import highSchools from "@/data/high-schools.json";
import schoolInsights from "@/data/school-insights.json";
import { ui } from "@/lib/i18n";
import { sameSchool } from "@/lib/school-preference";

const NAV_IDS=["overview","profile","colleges","opportunities","roadmap","applications","advisor","history","settings"];
const COUNTRY_LABEL={us:"US",uk:"UK",canada:"Canada",singapore:"Singapore",hk:"Hong Kong",australia:"Australia",europe:"Europe"};
const roundLabel={ED1:"ED I",ED2:"ED II",EA:"EA",EA2:"EA2",REA:"REA",SCEA:"SCEA",RD:"RD",RA:"RA",UC:"UC",UCAS:"UCAS",OX:"Oxbridge",ROLLING:"Rolling"};
const pct=x=>`${Math.round((Number(x)||0)*100)}%`;
const score=x=>Number.isFinite(Number(x))?Math.round(Number(x)):"—";
const chatCacheKey=userId=>`unipath.chat.advisor.${userId}`;
const projectCacheKey=userId=>`unipath.projects.original.v1.${userId}`;
const onboardingKey=userId=>`unipath.onboarding.v1.${userId}`;
function serverChatMessage(m){const role=m.role==="assistant"?"ai":"user",clientId=m.metadata?.client_id||m.metadata?.reply_to||null;return {id:m.id||null,role,text:m.content||"",created_at:m.created_at||new Date().toISOString(),client_id:clientId,persisted:true}}
function chatIdentity(m){if(m.client_id)return `${m.role}:${m.client_id}`;if(m.id)return `id:${m.id}`;return `${m.role}:${m.text}:${String(m.created_at||"").slice(0,16)}`}
function mergeChatMessages(...groups){const map=new Map();for(const group of groups){for(const m of (group||[])){if(!m?.text)continue;map.set(chatIdentity(m),m)}}return [...map.values()].sort((a,b)=>String(a.created_at||"").localeCompare(String(b.created_at||""))).slice(-100)}

function buildDraftPortfolio(predictions){
  const strategy=predictions?.round_strategy;
  const rows=[...(strategy?.recommended_plan||[]),...(strategy?.outside_common_app_plan||[])];
  return rows.map((p,i)=>({
    id:p.id||`model-${i}-${p.school_name}`,
    draft:true,
    school_name:p.school_name,
    program:p.program,
    major:p.major||predictions?.primary_major||null,
    round:p.round||"RD",
    probability:p.probability,
    probability_min:p.probability_min,
    probability_max:p.probability_max,
    tier:p.tier,
    status:"Planning",
    country:p.country||"us",
    rank:p.rank,
    source:p.round==="UC"?"outside_common_app":p.round==="EA"&&p.school_name==="MIT"?"outside_common_app":"model"
  }));
}

export default function Home(){
  const [supabase,setSupabase]=useState(null),[session,setSession]=useState(null),[authMode,setAuthMode]=useState("login");
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[authMsg,setAuthMsg]=useState(""),[rememberMe,setRememberMe]=useState(true);
  const [tab,setTab]=useState("overview"),[profile,setProfile]=useState({...EmptyProfile}),[predictions,setPredictions]=useState(null);
  const [plans,setPlans]=useState([]),[opps,setOpps]=useState([]),[savedOpps,setSavedOpps]=useState([]),[roadmap,setRoadmap]=useState([]),[generatedRoadmap,setGeneratedRoadmap]=useState(null),[generatedProjects,setGeneratedProjects]=useState(null);
  const [chat,setChat]=useState([]),[question,setQuestion]=useState(""),[chatHydrated,setChatHydrated]=useState(false),[history,setHistory]=useState([]),[isAdmin,setIsAdmin]=useState(false),[adminData,setAdminData]=useState(null);
  const [loading,setLoading]=useState(""),[importText,setImportText]=useState(""),[feedback,setFeedback]=useState("");
  const [language,setLanguage]=useState("en"),[density,setDensity]=useState("comfortable"),[theme,setTheme]=useState("dark");
  const [collegeTrack,setCollegeTrack]=useState("common20"),[collegeCountry,setCollegeCountry]=useState("all"),[collegeTier,setCollegeTier]=useState("all"),[collegeInstitution,setCollegeInstitution]=useState("all"),[collegeQuery,setCollegeQuery]=useState(""),[collegeSort,setCollegeSort]=useState("recommended"),[selectedCollege,setSelectedCollege]=useState(null);
  const [oppKind,setOppKind]=useState("all"),[oppQuery,setOppQuery]=useState(""),[selectedProject,setSelectedProject]=useState(null);
  const [showOnboarding,setShowOnboarding]=useState(false),[onboardingStep,setOnboardingStep]=useState(0);
  const [simulation,setSimulation]=useState(null),[strategy,setStrategy]=useState(null);
  const [adminSchool,setAdminSchool]=useState("Harvard"),[adminJson,setAdminJson]=useState('{\n  "sel": 0.035,\n  "source_note": "Verified current institutional source"\n}');
  const [demoPassword,setDemoPassword]=useState(""),[demoAccounts,setDemoAccounts]=useState([]);

  useEffect(()=>{
    try{
      const lang=localStorage.getItem("unipath.language");if(lang==="zh"||lang==="en")setLanguage(lang);
      const den=localStorage.getItem("unipath.density");if(den==="compact"||den==="comfortable")setDensity(den);
      const th=localStorage.getItem("unipath.theme");if(["system","light","dark"].includes(th))setTheme(th);
      const remembered=localStorage.getItem("unipath.remember_email");if(remembered){setEmail(remembered);setRememberMe(true)}
      const s=getSupabaseBrowser();setSupabase(s);s.auth.getSession().then(({data})=>setSession(data.session));
      const {data:{subscription}}=s.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>subscription.unsubscribe();
    }catch(e){setAuthMsg(e.message)}
  },[]);
  useEffect(()=>{if(session){setChatHydrated(false);bootstrap()}},[session]);
  useEffect(()=>{if(session&&tab==="opportunities"&&!opps.length)loadOpportunities()},[tab,session]);
  useEffect(()=>{try{localStorage.setItem("unipath.language",language)}catch{}},[language]);
  useEffect(()=>{try{localStorage.setItem("unipath.density",density)}catch{}},[density]);
  useEffect(()=>{
    try{localStorage.setItem("unipath.theme",theme)}catch{}
    if(typeof window==="undefined")return;
    const mq=window.matchMedia("(prefers-color-scheme: dark)");
    const apply=()=>{document.documentElement.dataset.theme=theme==="system"?(mq.matches?"dark":"light"):theme;document.documentElement.style.colorScheme=theme==="system"?(mq.matches?"dark":"light"):theme};
    apply();
    if(theme==="system"){mq.addEventListener?.("change",apply);return()=>mq.removeEventListener?.("change",apply)}
  },[theme]);
  useEffect(()=>{if(!session?.user?.id||!chatHydrated)return;try{const safe=chat.filter(m=>!m.ephemeral).slice(-100);localStorage.setItem(chatCacheKey(session.user.id),JSON.stringify(safe))}catch{}},[chat,chatHydrated,session?.user?.id]);
  useEffect(()=>{if(!session||tab!=="advisor")return;refreshChat()},[tab,session?.user?.id]);
  useEffect(()=>{if(!session?.user?.id||!generatedProjects)return;try{localStorage.setItem(projectCacheKey(session.user.id),JSON.stringify(generatedProjects))}catch{}},[generatedProjects,session?.user?.id]);
  useEffect(()=>{if(!session)return;const sync=()=>{if(document.visibilityState==="visible"&&tab==="advisor")refreshChat()};document.addEventListener("visibilitychange",sync);window.addEventListener("focus",sync);return()=>{document.removeEventListener("visibilitychange",sync);window.removeEventListener("focus",sync)}},[session?.user?.id,tab]);

  async function api(action,body={}){
    if(!session?.access_token)throw new Error("Please log in.");
    let res;
    try{
      res=await fetch("/api/unipath",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,...body})});
    }catch(e){
      throw new Error("Network request failed. Refresh the page and retry. If it repeats, check the latest Vercel runtime log.");
    }
    const raw=await res.text();let data={};
    try{data=raw?JSON.parse(raw):{}}catch{}
    if(!res.ok)throw new Error(data.error||raw||`Request failed (${res.status})`);
    return data;
  }
  async function bootstrap(){
    try{
      setLoading("bootstrap");
      const d=await api("bootstrap");
      setIsAdmin(!!d.is_admin);
      if(d.profile)setProfile({...EmptyProfile,...d.profile});
      let loadedPlans=d.plans||[];
      if(d.predictions){setPredictions(d.predictions);if(loadedPlans.length){try{const synced=await api("sync_plans",{predictions:d.predictions});loadedPlans=synced.plans||loadedPlans}catch{}}}
      setPlans(loadedPlans);setSavedOpps(d.saved_opportunities||[]);setRoadmap(d.roadmap||[]);
      try{const cachedProjects=JSON.parse(localStorage.getItem(projectCacheKey(session.user.id))||"null");if(cachedProjects?.projects?.length)setGeneratedProjects(cachedProjects)}catch{}
      let cached=[];try{cached=JSON.parse(localStorage.getItem(chatCacheKey(session.user.id))||"[]")}catch{}
      setChat(mergeChatMessages(cached,(d.messages||[]).map(serverChatMessage)));setChatHydrated(true);
      try{if(!localStorage.getItem(onboardingKey(session.user.id))){setOnboardingStep(0);setShowOnboarding(true)}}catch{}
    }catch(e){alert(e.message)}finally{setLoading("")}
  }
  async function signIn(e){e.preventDefault();setAuthMsg("");try{if(!supabase)throw new Error("Supabase is not configured.");if(authMode==="signup"){const {error}=await supabase.auth.signUp({email,password});if(error)throw error;setAuthMsg("Account created. Check email if confirmation is enabled.")}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}try{if(rememberMe)localStorage.setItem("unipath.remember_email",email);else localStorage.removeItem("unipath.remember_email")}catch{}}catch(e){setAuthMsg(e.message)}}
  async function logout(){await supabase?.auth.signOut();setSession(null)}
  const update=(k,v)=>setProfile(p=>({...p,[k]:v}));
  async function saveProfile(){try{setLoading("save");const d=await api("save_profile",{profile});setProfile({...EmptyProfile,...d.profile})}catch(e){alert(e.message)}finally{setLoading("")}}
  async function syncPlansWithPredictions(nextPredictions){
    if(!plans.length||!nextPredictions?.schools?.length)return;
    try{const d=await api("sync_plans",{predictions:nextPredictions});setPlans(d.plans||[]);setSimulation(null)}catch(e){console.warn("Plan sync failed",e)}
  }
  async function importProfile(){try{setLoading("import");const d=await api("analyze",{text:importText,age_band:profile.age_band});setProfile({...EmptyProfile,...d.profile});setPredictions(d.predictions);setPlans([]);setSimulation(null);setStrategy(null);setTab("colleges")}catch(e){alert(e.message)}finally{setLoading("")}}
  async function runPrediction(nextProfile=profile){try{setLoading("predict");const d=await api("predict",{profile:nextProfile,primary_major:nextProfile.primary_major,secondary_major:nextProfile.secondary_major,use_ai:true});if(d.profile)setProfile({...EmptyProfile,...d.profile});setPredictions(d.predictions);setSelectedCollege(null);await syncPlansWithPredictions(d.predictions);setTab("colleges")}catch(e){alert(e.message)}finally{setLoading("")}}
  async function addSchool(row){try{const rule=roundRules[row.school]||{default:row.country==="uk"?"UCAS":"RD"};const d=await api("save_plan",{plan:{school_name:row.school,program:row.program,major:row.major,round:rule.default,probability:row.probability,probability_min:row.interval[0],probability_max:row.interval[1],tier:row.tier,status:"Planning",country:row.country,rank:row.rank}});setPlans(p=>[...p.filter(x=>x.school_name!==row.school),d.plan]);setSimulation(null)}catch(e){alert(e.message)}}
  async function saveSuggestedPortfolio(draft){if(!draft?.length)return;try{setLoading("saveDraft");const d=await api("save_plan_batch",{plans:draft});setPlans(d.plans||[]);setSimulation(null)}catch(e){alert(e.message)}finally{setLoading("")}}
  async function changePlan(plan,patch){try{const d=await api("save_plan",{plan:{...plan,...patch}});setPlans(p=>p.map(x=>x.id===plan.id?d.plan:x));setSimulation(null)}catch(e){alert(e.message)}}
  async function deletePlan(plan){try{await api("delete_plan",{id:plan.id});setPlans(p=>p.filter(x=>x.id!==plan.id));setSimulation(null)}catch(e){alert(e.message)}}
  async function loadOpportunities(){try{setLoading("opps");const d=await api("opportunities",{profile,kind:oppKind,query:oppQuery,limit:80});setOpps(d.items||[])}catch(e){alert(e.message)}finally{setLoading("")}}
  async function generateProjects(){try{setLoading("projects");const d=await api("generate_projects",{profile,predictions,language});setGeneratedProjects(d.projects||null)}catch(e){alert(e.message)}finally{setLoading("")}}
  async function addGeneratedProject(project){try{setLoading("addProject");const due=new Date();due.setMonth(due.getMonth()+Math.max(2,Math.min(10,Math.ceil((Number(project.duration_weeks)||8)/4))));const item={title:project.title,item_type:"original_project",due_window:due.toISOString().slice(0,7),priority:"high",status:"todo",why:`${project.why_this_student||""}${(project.steps||[]).length?` Steps: ${(project.steps||[]).join(" → ")}`:""}`.trim(),success_metric:[(project.deliverables||[]).length?`Deliverables: ${(project.deliverables||[]).join(", ")}`:"",(project.success_metrics||[]).length?`Success: ${(project.success_metrics||[]).join(", ")}`:""].filter(Boolean).join(" · "),source_id:"custom-project"};const d=await api("save_roadmap_item",{item});setRoadmap(p=>[...p,d.item]);setTab("roadmap")}catch(e){alert(e.message)}finally{setLoading("")}}
  async function saveOpportunity(o){try{const d=await api("save_opportunity",{opportunity_id:o.id});setSavedOpps(p=>[...p.filter(x=>x.opportunity_id!==o.id),d.item])}catch(e){alert(e.message)}}
  async function removeOpportunity(o){try{await api("delete_saved_opportunity",{opportunity_id:o.id});setSavedOpps(p=>p.filter(x=>x.opportunity_id!==o.id))}catch(e){alert(e.message)}}
  async function generateRoadmap(){try{setLoading("roadmap");const d=await api("generate_roadmap",{profile,predictions,language});setGeneratedRoadmap(d.roadmap)}catch(e){alert(e.message)}finally{setLoading("")}}
  async function acceptRoadmap(){if(!generatedRoadmap?.items?.length)return;try{setLoading("acceptRoadmap");const d=await api("accept_roadmap",{items:generatedRoadmap.items});setRoadmap(p=>[...p,...(d.items||[])]);setGeneratedRoadmap(null)}catch(e){alert(e.message)}finally{setLoading("")}}
  async function updateRoadmapItem(item,patch){try{const d=await api("save_roadmap_item",{item:{...item,...patch}});setRoadmap(p=>p.map(x=>x.id===item.id?d.item:x))}catch(e){alert(e.message)}}
  async function deleteRoadmapItem(item){try{await api("delete_roadmap_item",{id:item.id});setRoadmap(p=>p.filter(x=>x.id!==item.id))}catch(e){alert(e.message)}}
  async function clearStaleRoadmap(){try{setLoading("clearStale");const d=await api("clear_stale_roadmap");setRoadmap(d.items||[])}catch(e){alert(e.message)}finally{setLoading("")}}
  async function refreshChat(){if(!session?.user?.id)return;try{const d=await api("chat_history");setChat(c=>mergeChatMessages(c,(d.messages||[]).map(serverChatMessage)))}catch(e){console.warn("Chat sync failed",e)}}
  async function askAI(){const q=question.trim();if(!q||loading==="chat")return;const clientId=globalThis.crypto?.randomUUID?.()||`msg-${Date.now()}-${Math.random().toString(36).slice(2)}`;const optimistic={role:"user",text:q,created_at:new Date().toISOString(),client_id:clientId,persisted:false};setChat(c=>mergeChatMessages(c,[optimistic]));setQuestion("");try{setLoading("chat");const d=await api("counsel",{question:q,profile,predictions,plans,language,client_id:clientId});const persisted=[d.user_message,d.assistant_message].filter(Boolean).map(serverChatMessage);setChat(c=>mergeChatMessages(c,persisted.length?persisted:[{role:"ai",text:d.answer,created_at:new Date().toISOString(),client_id:clientId,persisted:true}]))}catch(e){setChat(c=>mergeChatMessages(c,[{role:"ai",text:"I couldn't complete that response. Your question is saved; retry when you're back online.",created_at:new Date().toISOString(),client_id:clientId,ephemeral:true,error:true}]))}finally{setLoading("")}}
  async function clearChat(){try{await api("clear_chat");setChat([]);if(session?.user?.id)localStorage.removeItem(chatCacheKey(session.user.id))}catch(e){alert(e.message)}}
  async function toggleLac(enabled){const next={...profile,include_liberal_arts_colleges:enabled};setProfile(next);setCollegeInstitution(enabled?"all":"university");await runPrediction(next)}
  async function simulate(runs=2000,sourcePlans=plans){try{setLoading("simulate");const d=await api("simulate",{plans:sourcePlans,runs});setSimulation(d)}catch(e){alert(e.message)}finally{setLoading("")}}
  async function optimize(sourcePlans=plans){try{setLoading("strategy");setStrategy(await api("optimize_strategy",{plans:sourcePlans}))}catch(e){alert(e.message)}finally{setLoading("")}}
  async function loadHistory(){try{const d=await api("history");setHistory(d.runs||[]);setTab("history")}catch(e){alert(e.message)}}
  async function loadAdmin(){try{const d=await api("admin_stats");setAdminData(d);setTab("admin")}catch(e){alert(e.message)}}
  async function saveOverride(){try{await api("admin_save_override",{school_name:adminSchool,data:JSON.parse(adminJson)});await loadAdmin()}catch(e){alert(e.message)}}
  async function seedDemoAccounts(){try{setLoading("demo");const d=await api("admin_seed_demo_accounts",{password:demoPassword});setDemoAccounts(d.accounts||[])}catch(e){alert(e.message)}finally{setLoading("")}}
  async function sendFeedback(){if(!feedback.trim())return;try{await api("feedback",{message:feedback});setFeedback("")}catch(e){alert(e.message)}}
  function finishOnboarding(target="profile"){try{if(session?.user?.id)localStorage.setItem(onboardingKey(session.user.id),"done")}catch{}setShowOnboarding(false);setOnboardingStep(0);if(target)setTab(target)}
  function restartOnboarding(){try{if(session?.user?.id)localStorage.removeItem(onboardingKey(session.user.id))}catch{}setOnboardingStep(0);setShowOnboarding(true)}

  function addActivity(){update("activities",[...(profile.activities||[]),{name:"",description:"",category:"other",status:"ongoing",years:null,hours_per_week:null,role:"",impact_scope:"unknown",measurable_outcome:"",major_related:false}])}
  function setActivity(i,k,v){update("activities",profile.activities.map((a,j)=>j===i?{...a,[k]:v}:a))}
  function addAward(){update("awards",[...(profile.awards||[]),{name:"",level:"unknown",status:"earned",major_related:false}])}
  function setAward(i,k,v){update("awards",profile.awards.map((a,j)=>j===i?{...a,[k]:v}:a))}

  const collegeRows=useMemo(()=>{
    const source=collegeTrack==="common20"?(predictions?.us_common_app_20||[]):collegeTrack==="us_extra"?(predictions?.us_outside_common_app||[]):collegeTrack==="uk"?(predictions?.uk_track||[]):(predictions?.schools||[]);
    const q=collegeQuery.toLowerCase();const cap=Number(profile.us_rank_cap)||null;const tierOK=s=>collegeTrack==="uk"||collegeTier==="all"||s.tier===collegeTier;const rankedUS=s=>["National University","National Liberal Arts College"].includes(s.usnews_system);const rankOK=s=>!cap||s.country!=="us"||!rankedUS(s)||Number(s.usnews_2026)<=cap;const institutionOK=s=>collegeTrack==="uk"||collegeInstitution==="all"||(s.country==="us"&&(collegeInstitution==="lac"?s.institution_type==="liberal_arts_college":s.institution_type!=="liberal_arts_college"));
    const filtered=source.filter(s=>(collegeCountry==="all"||s.country===collegeCountry)&&tierOK(s)&&rankOK(s)&&institutionOK(s)&&(!q||`${s.school} ${s.program}`.toLowerCase().includes(q)));
    if(collegeSort==="recommended")return filtered;
    const num=v=>Number.isFinite(Number(v))&&Number(v)>0?Number(v):99999;const prefValue=s=>{const p=(profile.school_preferences||[]).find(x=>sameSchool(x.school_name,s.school));return Number(p?.interest)||0};
    const usnGroup=s=>s.usnews_system==="National University"?0:s.usnews_system==="National Liberal Arts College"?1:s.usnews_system?.includes("Global")?2:3;const sorters={qs:(a,b)=>num(a.qs_2026)-num(b.qs_2026),usnews:(a,b)=>usnGroup(a)-usnGroup(b)||num(a.usnews_2026)-num(b.usnews_2026),chance_high:(a,b)=>(Number(b.probability)||0)-(Number(a.probability)||0),chance_low:(a,b)=>(Number(a.probability)||0)-(Number(b.probability)||0),course_fit:(a,b)=>(Number(b.academic_fit)||0)-(Number(a.academic_fit)||0),project_fit:(a,b)=>(Number(b.project_fit)||0)-(Number(a.project_fit)||0),preference:(a,b)=>prefValue(b)-prefValue(a)};
    return [...filtered].sort(sorters[collegeSort]||(()=>0));
  },[predictions,collegeTrack,collegeCountry,collegeTier,collegeInstitution,collegeQuery,collegeSort,profile.us_rank_cap,profile.school_preferences]);
  const draftPlans=useMemo(()=>buildDraftPortfolio(predictions),[predictions]);
  const effectiveApplicationPlans=draftPlans.length?draftPlans:plans;
  useEffect(()=>{if(predictions?.round_strategy)setStrategy({strategy:predictions.round_strategy,validation:{errors:[],warnings:[]}})},[predictions]);
  const completedRoadmap=roadmap.filter(x=>x.status==="done").length;

  if(!session)return <AuthScreen mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} remember={rememberMe} setRemember={setRememberMe} submit={signIn} msg={authMsg} language={language} setLanguage={setLanguage}/>;
  const hs=highSchools.find(h=>h.id===profile.high_school_id);const copy=ui(language);

  return <div className={`shell ${density==="compact"?"compactUI":""}`}>
    <aside className="rail">
      <div className="brand"><div className="mark">U</div><div><b>UniPath</b><small>Admissions OS</small></div></div>
      <nav>{NAV_IDS.map(id=><button key={id} className={tab===id?"active":""} onClick={()=>id==="history"?loadHistory():setTab(id)}>{copy.nav[id]}</button>)}{isAdmin&&<button className={tab==="admin"?"active":""} onClick={loadAdmin}>{copy.nav.admin}</button>}</nav>
      <div className="account"><span>{session.user.email}</span><button onClick={logout}>{copy.logout}</button></div>
    </aside>

    <main className="workspace">
      <header className="mast"><div><span className="kicker">UNIPATH / {tab.toUpperCase()}</span><h1>{copy.titles[tab]||"UniPath"}</h1><p>{copy.subtitles[tab]||""}</p></div><div className="mastActions"><button className="quiet" onClick={saveProfile}>{loading==="save"?"Saving…":copy.save}</button><button className="solid" onClick={()=>runPrediction()}>{loading==="predict"?copy.analyze:copy.run}</button></div></header>

      {tab==="overview"&&<Overview profile={profile} predictions={predictions} plans={plans} roadmap={roadmap} completedRoadmap={completedRoadmap} hs={hs} go={setTab} runPrediction={runPrediction}/>}      
      {tab==="profile"&&<ProfileEditor profile={profile} update={update} importText={importText} setImportText={setImportText} importProfile={importProfile} loading={loading} addActivity={addActivity} setActivity={setActivity} addAward={addAward} setAward={setAward}/>}      
      {tab==="colleges"&&<Colleges profile={profile} rows={collegeRows} predictions={predictions} plans={plans} addSchool={addSchool} track={collegeTrack} setTrack={v=>{setCollegeTrack(v);setSelectedCollege(null)}} country={collegeCountry} setCountry={setCollegeCountry} tier={collegeTier} setTier={setCollegeTier} institution={collegeInstitution} setInstitution={setCollegeInstitution} query={collegeQuery} setQuery={setCollegeQuery} sort={collegeSort} setSort={setCollegeSort} run={runPrediction} loading={loading} rankCap={profile.us_rank_cap} setRankCap={v=>{const next={...profile,us_rank_cap:v};setProfile(next);runPrediction(next)}} lacEnabled={profile.include_liberal_arts_colleges!==false} toggleLac={toggleLac} selected={selectedCollege} openCollege={setSelectedCollege} closeCollege={()=>setSelectedCollege(null)}/>}      
      {tab==="opportunities"&&<Opportunities items={opps} saved={savedOpps} kind={oppKind} setKind={setOppKind} query={oppQuery} setQuery={setOppQuery} search={loadOpportunities} save={saveOpportunity} remove={removeOpportunity} loading={loading} generated={generatedProjects} generateProjects={generateProjects} addProject={addGeneratedProject} selectedProject={selectedProject} openProject={setSelectedProject} closeProject={()=>setSelectedProject(null)}/>}      
      {tab==="roadmap"&&<Roadmap profile={profile} items={roadmap} generated={generatedRoadmap} generate={generateRoadmap} accept={acceptRoadmap} update={updateRoadmapItem} remove={deleteRoadmapItem} clearStale={clearStaleRoadmap} savedOpps={savedOpps} loading={loading}/>}      
      {tab==="applications"&&<Applications predictions={predictions} plans={plans} draftPlans={draftPlans} effectivePlans={effectiveApplicationPlans} saveDraft={saveSuggestedPortfolio} change={changePlan} remove={deletePlan} strategy={strategy} simulate={simulate} simulation={simulation} loading={loading}/>}      
      {tab==="advisor"&&<Advisor chat={chat} question={question} setQuestion={setQuestion} send={askAI} clear={clearChat} loading={loading}/>}      
      {tab==="history"&&<History rows={history}/>}      
      {tab==="settings"&&<Settings language={language} setLanguage={setLanguage} density={density} setDensity={setDensity} theme={theme} setTheme={setTheme} profile={profile} setProfile={setProfile} saveProfile={saveProfile} restartOnboarding={restartOnboarding}/>}
      {tab==="admin"&&isAdmin&&<Admin data={adminData} school={adminSchool} setSchool={setAdminSchool} json={adminJson} setJson={setAdminJson} save={saveOverride} demoPassword={demoPassword} setDemoPassword={setDemoPassword} demoAccounts={demoAccounts} seedDemo={seedDemoAccounts} loading={loading}/>}      
      {showOnboarding&&<Onboarding language={language} step={onboardingStep} setStep={setOnboardingStep} finish={finishOnboarding}/>}

      <div className="feedback"><span>Something wrong or missing?</span><input value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Tell us what the model got wrong."/><button onClick={sendFeedback}>Send</button></div>
      <footer>Planning model, not an admissions decision system. University policies, program availability, deadlines and aggregate school-outcome data should be verified from current official sources.</footer>
    </main>
  </div>;
}

function AuthScreen({mode,setMode,email,setEmail,password,setPassword,remember,setRemember,submit,msg,language,setLanguage}){
  const zh=language==="zh";
  return <main className="auth authModern"><section className="authHero"><div className="brand authBrand"><div className="mark">U</div><div><b>UniPath</b><small>Admissions OS</small></div></div><div className="authCopy"><span className="kicker">UNIPATH</span><h1>{zh?"把申请规划，收进一条清晰路径。":"Plan what matters next."}</h1><p>{zh?"档案、选校、项目、时间线和申请策略持续同步，不需要每次重新开始。":"Your profile, college list, projects, roadmap and application strategy stay in one continuous system."}</p><div className="authSignals"><span><b>{schools.length}</b>{zh?" 所学校":" schools"}</span><span><b>{majors.length}</b>{zh?" 个专业方向":" majors"}</span><span><b>1</b>{zh?" 条持续规划":" persistent plan"}</span></div></div></section><form className="authCard" onSubmit={submit}><div className="authTop"><div><span className="overline">{mode==="login"?(zh?"欢迎回来":"WELCOME BACK"):(zh?"开始使用":"GET STARTED")}</span><h2>{mode==="login"?(zh?"登录 UniPath":"Sign in"):(zh?"创建账户":"Create account")}</h2></div><select className="languageMini" value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="zh">简体中文</option></select></div><label>{zh?"邮箱":"Email"}<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>{zh?"密码":"Password"}<input type="password" autoComplete={mode==="login"?"current-password":"new-password"} value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/></label>{mode==="login"&&<><div className="demoLogin"><span>{zh?"同学测试账户":"Classmate demo account"}</span><select value={email.startsWith("unipath.demo")?email:""} onChange={e=>{if(e.target.value)setEmail(e.target.value)}}><option value="">{zh?"可选：选择管理员创建的测试账户":"Optional: choose a demo user"}</option>{[1,2,3,4,5].map(n=>{const v=`unipath.demo${n}@example.com`;return <option key={v} value={v}>{v}</option>})}</select></div><label className="rememberRow"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span>{zh?"记住邮箱":"Remember email"}</span></label></>}<button className="solid authPrimary" type="submit">{mode==="login"?(zh?"继续":"Continue"):(zh?"创建账户":"Create account")}</button>{msg&&<div className="notice">{msg}</div>}<button type="button" className="textButton authSwitch" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?(zh?"创建新账户":"Create an account"):(zh?"已有账户？登录":"Already have an account?")}</button><small className="authHint">{zh?"密码由浏览器密码管理器处理；UniPath 不会把明文密码写入本地存储。":"Passwords are handled by your browser password manager; UniPath does not write raw passwords to local storage."}</small></form></main>
}

function Overview({profile,predictions,plans,roadmap,completedRoadmap,hs,go,runPrediction}){
  const s=predictions?.scores||{};const common=predictions?.us_common_app_20||[];const lacCount=predictions?.list_calibration?.selected_liberal_arts_colleges||common.filter(x=>x.institution_type==="liberal_arts_college").length;
  return <section className="overviewStack">
    <article className="panel overviewHero"><div className="overviewMain"><span className="overline">CURRENT PATH</span><h2>{profile.primary_major||"Choose a primary direction"}</h2><p>{profile.profile_summary||"Complete the profile once. UniPath will keep the college model, roadmap and strategy synchronized as your evidence changes."}</p><div className="facts"><span>{profile.current_grade==="unknown"?"Grade not set":`Grade ${profile.current_grade}`}</span><span>{profile.sat?`SAT ${profile.sat}`:"Test score not set"}</span><span>{hs?.name||profile.high_school_name||"High school not set"}</span></div><div className="row"><button className="solid" onClick={()=>runPrediction()}>Refresh model</button><button className="quiet" onClick={()=>go("profile")}>Edit profile</button></div></div><div className="overviewScore"><span>Profile signal</span><strong>{score(s.overall)}</strong><small>{predictions?"Latest hybrid model":"Run your first prediction"}</small></div></article>
    <section className="overviewGrid"><article className="panel overviewActions"><span className="overline">NEXT</span><ActionLine n="01" title="Strengthen the evidence" text="Update courses, outputs and measurable activity results." onClick={()=>go("profile")}/><ActionLine n="02" title="Review the college mix" text={`${common.length}/20 Common App slots · ${lacCount} liberal arts college${lacCount===1?"":"s"}.`} onClick={()=>go("colleges")}/><ActionLine n="03" title="Build the next year" text="Turn gaps into a dated roadmap and original projects." onClick={()=>go("roadmap")}/></article><article className="panel overviewPulse"><span className="overline">APPLICATION PULSE</span><div className="pulseGrid"><Mini label="Common App" value={`${common.length}/20`}/><Mini label="Liberal arts" value={lacCount}/><Mini label="Roadmap done" value={`${completedRoadmap}/${roadmap.length||0}`}/></div>{predictions?<><div className="tierStrip compactTiers">{["Lottery","Reach","Target","Likely"].map(t=><div key={t}><b>{common.filter(x=>t==="Lottery"?["Lottery","Super Reach"].includes(x.tier):x.tier===t).length}</b><span>{t==="Lottery"?"High reach":t}</span></div>)}</div><button className="quiet overviewLink" onClick={()=>go("applications")}>Open application strategy →</button></>:<p className="muted">Run a prediction to see the portfolio shape and application strategy.</p>}</article></section>
  </section>
}

function ProfileEditor({profile,update,importText,setImportText,importProfile,loading,addActivity,setActivity,addAward,setAward}){
  const chooseHS=e=>{const id=e.target.value;const h=highSchools.find(x=>x.id===id);update("high_school_id",id||null);update("high_school_name",h?.name||null);update("school_country",h?.country||null)};
  const setArray=(key,idx,patch)=>update(key,(profile[key]||[]).map((x,i)=>i===idx?{...x,...patch}:x));
  const removeArray=(key,idx)=>update(key,(profile[key]||[]).filter((_,i)=>i!==idx));
  const addAP=()=>update("ap_courses",[...(profile.ap_courses||[]),{subject:"",score:null,status:"completed"}]);
  const addIB=()=>update("ib_courses",[...(profile.ib_courses||[]),{subject:"",level:"HL",score:null,status:"completed"}]);
  const addAL=()=>update("alevel_courses",[...(profile.alevel_courses||[]),{subject:"",grade:"unknown",status:"completed"}]);
  const addPref=()=>update("school_preferences",[...(profile.school_preferences||[]),{school_name:"",interest:null,note:""}]);
  return <section className="stack">
    <article className="panel"><div className="panelHead"><div><span className="overline">CONTEXT</span><h3>School & application direction</h3></div></div><div className="formGrid three">
      <Field label="High school"><select value={profile.high_school_id||""} onChange={chooseHS}><option value="">Select or use Other</option>{highSchools.map(h=><option key={h.id} value={h.id}>{h.name}{h.name_zh?` / ${h.name_zh}`:""}</option>)}</select></Field>
      <Field label="School name / custom"><input value={profile.high_school_name||""} onChange={e=>update("high_school_name",e.target.value)} placeholder="Type your school if not listed"/></Field>
      <Field label="Current grade"><select value={profile.current_grade} onChange={e=>update("current_grade",e.target.value)}>{["8","9","10","11","12","gap","unknown"].map(x=><option key={x}>{x}</option>)}</select></Field>
      <Field label="Graduation year"><input type="number" value={profile.graduation_year??""} onChange={e=>update("graduation_year",e.target.value?Number(e.target.value):null)}/></Field>
      <Field label="Applicant type"><select value={profile.applicant_type} onChange={e=>update("applicant_type",e.target.value)}>{["china_international","other_international","us_domestic","uk_home","unknown"].map(x=><option key={x}>{x}</option>)}</select></Field>
      <Field label="Primary major"><select value={profile.primary_major||""} onChange={e=>update("primary_major",e.target.value||null)}><option value="">Select</option>{majors.map(m=><option key={m.slug} value={m.label}>{m.label}</option>)}</select></Field>
      <Field label="Secondary major"><select value={profile.secondary_major||""} onChange={e=>update("secondary_major",e.target.value||null)}><option value="">None</option>{majors.map(m=><option key={m.slug} value={m.label}>{m.label}</option>)}</select></Field>
    </div><div className="countryChecks">{Object.entries(COUNTRY_LABEL).map(([id,label])=><label key={id}><input type="checkbox" checked={(profile.intended_countries||[]).includes(id)} onChange={e=>update("intended_countries",e.target.checked?[...(profile.intended_countries||[]),id]:(profile.intended_countries||[]).filter(x=>x!==id))}/>{label}</label>)}</div></article>

    <article className="panel"><div className="panelHead"><div><span className="overline">ACADEMICS</span><h3>Evaluate the actual subjects, not an AP/IB/A-level total</h3></div><span className="muted">Major prerequisites and subject relevance are scored separately.</span></div><div className="formGrid four">
      <Field label="Curriculum"><select value={profile.curriculum} onChange={e=>update("curriculum",e.target.value)}>{["ap","ib","alevel","us","other","unknown"].map(x=><option key={x}>{x}</option>)}</select></Field>
      <Field label="Grade band"><select value={profile.grade_band} onChange={e=>update("grade_band",e.target.value)}>{["top1","top5","top10","top25","mid","unknown"].map(x=><option key={x}>{x}</option>)}</select></Field>
      <Field label="GPA / transcript context"><input value={profile.gpa_description||""} onChange={e=>update("gpa_description",e.target.value)} placeholder="3.92 UW / 4.55 W, school scale…"/></Field>
      <Field label="SAT"><input type="number" value={profile.sat??""} onChange={e=>update("sat",e.target.value?Number(e.target.value):null)}/></Field>
      <Field label="ACT"><input type="number" value={profile.act??""} onChange={e=>update("act",e.target.value?Number(e.target.value):null)}/></Field>
      <Field label="TOEFL"><input type="number" value={profile.toefl??""} onChange={e=>update("toefl",e.target.value?Number(e.target.value):null)}/></Field>
      <Field label="Rigor"><select value={profile.academic_rigor} onChange={e=>update("academic_rigor",e.target.value)}>{["highest","strong","average","unknown"].map(x=><option key={x}>{x}</option>)}</select></Field>
      <Field label="Aid need"><select value={profile.aid_need} onChange={e=>update("aid_need",e.target.value)}>{["none","some","high","unknown"].map(x=><option key={x}>{x}</option>)}</select></Field>
    </div>

    {profile.curriculum==="ap"&&<CoursePanel title="AP subjects" hint="Score each AP by subject and status. A 5 in a major-foundation course is not treated the same as a 5 in an unrelated course." add={addAP}>
      {(profile.ap_courses||[]).map((c,i)=><div className="courseRow ap" key={i}><input value={c.subject} onChange={e=>setArray("ap_courses",i,{subject:e.target.value})} placeholder="AP subject, e.g. Chemistry"/><select value={c.score??""} onChange={e=>setArray("ap_courses",i,{score:e.target.value?Number(e.target.value):null})}><option value="">No score yet</option>{[5,4,3,2,1].map(x=><option key={x} value={x}>{x}</option>)}</select><select value={c.status} onChange={e=>setArray("ap_courses",i,{status:e.target.value})}>{["completed","current","planned"].map(x=><option key={x}>{x}</option>)}</select><button className="iconDanger" onClick={()=>removeArray("ap_courses",i)}>×</button></div>)}
    </CoursePanel>}
    {profile.curriculum==="ib"&&<CoursePanel title="IB subjects" hint="HL/SL and predicted/earned subject scores are evaluated individually against the intended major." add={addIB}>
      {(profile.ib_courses||[]).map((c,i)=><div className="courseRow ib" key={i}><input value={c.subject} onChange={e=>setArray("ib_courses",i,{subject:e.target.value})} placeholder="IB subject, e.g. Physics"/><select value={c.level} onChange={e=>setArray("ib_courses",i,{level:e.target.value})}>{["HL","SL","unknown"].map(x=><option key={x}>{x}</option>)}</select><select value={c.score??""} onChange={e=>setArray("ib_courses",i,{score:e.target.value?Number(e.target.value):null})}><option value="">No score yet</option>{[7,6,5,4,3,2,1].map(x=><option key={x} value={x}>{x}</option>)}</select><select value={c.status} onChange={e=>setArray("ib_courses",i,{status:e.target.value})}>{["completed","current","planned"].map(x=><option key={x}>{x}</option>)}</select><button className="iconDanger" onClick={()=>removeArray("ib_courses",i)}>×</button></div>)}
    </CoursePanel>}
    {profile.curriculum==="alevel"&&<CoursePanel title="A-level subjects" hint="A-level subject choice and grade are evaluated against the intended field; the model does not use only an A* count." add={addAL}>
      {(profile.alevel_courses||[]).map((c,i)=><div className="courseRow alevel" key={i}><input value={c.subject} onChange={e=>setArray("alevel_courses",i,{subject:e.target.value})} placeholder="A-level subject, e.g. Mathematics"/><select value={c.grade} onChange={e=>setArray("alevel_courses",i,{grade:e.target.value})}>{["A*","A","B","C","D","E","U","predicted","unknown"].map(x=><option key={x}>{x}</option>)}</select><select value={c.status} onChange={e=>setArray("alevel_courses",i,{status:e.target.value})}>{["completed","current","planned"].map(x=><option key={x}>{x}</option>)}</select><button className="iconDanger" onClick={()=>removeArray("alevel_courses",i)}>×</button></div>)}
    </CoursePanel>}
    {!["ap","ib","alevel"].includes(profile.curriculum)&&<div className="notice">Select AP, IB or A-level to enter subject-level courses. Other curricula continue to use transcript context + rigor until a dedicated course schema is added.</div>}
    </article>

    <article className="panel"><div className="panelHead"><div><span className="overline">SCHOOL PREFERENCES</span><h3>Preference matters for binding ED strategy</h3></div><button className="quiet" onClick={addPref}>Add preference</button></div><p className="muted">0–10 is personal willingness to attend, not prestige. The model can recommend an ED school automatically, but it should not manufacture a binding commitment to a school you do not actually prefer.</p>{!(profile.school_preferences||[]).length?<Empty text="Optional: add schools you genuinely like. This improves ED/REA route selection."/>:<div className="preferenceList">{profile.school_preferences.map((x,i)=><div className="preferenceRow" key={i}><input value={x.school_name||""} onChange={e=>setArray("school_preferences",i,{school_name:e.target.value})} placeholder="School name"/><input type="number" min="0" max="10" step="0.5" value={x.interest??""} onChange={e=>setArray("school_preferences",i,{interest:e.target.value===""?null:Number(e.target.value)})} placeholder="0–10"/><input value={x.note||""} onChange={e=>setArray("school_preferences",i,{note:e.target.value})} placeholder="Why / constraints (optional)"/><button className="iconDanger" onClick={()=>removeArray("school_preferences",i)}>×</button></div>)}</div>}</article>

    <article className="panel"><div className="panelHead"><div><span className="overline">ACTIVITIES</span><h3>Project content is part of the model</h3></div><button className="quiet" onClick={addActivity}>Add activity</button></div><p className="muted">Describe what you actually researched, built, measured, wrote or changed. The probability model reads this text for major fit and interdisciplinarity; category labels alone are not enough.</p>{!profile.activities.length?<Empty text="No activities yet."/>:<div className="editorList">{profile.activities.map((a,i)=><div className="activityEdit" key={i}><input value={a.name} onChange={e=>setActivity(i,"name",e.target.value)} placeholder="Activity"/><select value={a.status||"unknown"} onChange={e=>setActivity(i,"status",e.target.value)}>{["completed","ongoing","planned","unknown"].map(x=><option key={x}>{x}</option>)}</select><select value={a.category} onChange={e=>setActivity(i,"category",e.target.value)}>{["research","stem","business","service","sports","arts","humanities","social_science","work","family_responsibility","other"].map(x=><option key={x}>{x}</option>)}</select><input value={a.role||""} onChange={e=>setActivity(i,"role",e.target.value)} placeholder="Role"/><input type="number" min="0" max="12" step="0.1" value={a.years??""} onChange={e=>setActivity(i,"years",e.target.value?Math.max(0,Number(e.target.value)):null)} placeholder="Years"/><input type="number" min="0" max="80" value={a.hours_per_week??""} onChange={e=>setActivity(i,"hours_per_week",e.target.value?Math.max(0,Number(e.target.value)):null)} placeholder="h/week"/><select value={a.impact_scope} onChange={e=>setActivity(i,"impact_scope",e.target.value)}>{["self","school","local","regional","national","international","unknown"].map(x=><option key={x}>{x}</option>)}</select><input className="wide" value={a.measurable_outcome||""} onChange={e=>setActivity(i,"measurable_outcome",e.target.value)} placeholder="Concrete outcome / finished output"/><button className="iconDanger" onClick={()=>update("activities",profile.activities.filter((_,j)=>j!==i))}>×</button><textarea className="activityDescription" value={a.description||""} onChange={e=>setActivity(i,"description",e.target.value)} placeholder="What did you actually do? Methods, materials, code, experiments, writing, users, data, iterations, impact…"/></div>)}</div>}</article>

    <article className="panel"><div className="panelHead"><div><span className="overline">AWARDS & OUTPUTS</span><h3>External validation and finished work</h3></div><button className="quiet" onClick={addAward}>Add award</button></div><div className="awardList">{profile.awards.map((a,i)=><div className="awardEdit" key={i}><input value={a.name} onChange={e=>setAward(i,"name",e.target.value)} placeholder="Award"/><select value={a.status||"earned"} onChange={e=>setAward(i,"status",e.target.value)}><option>earned</option><option>planned</option><option>unknown</option></select><select value={a.level} onChange={e=>setAward(i,"level",e.target.value)}>{["school","regional","national","international","elite","unknown"].map(x=><option key={x}>{x}</option>)}</select><button className="iconDanger" onClick={()=>update("awards",profile.awards.filter((_,j)=>j!==i))}>×</button></div>)}</div><Field label="Distinctive outputs — one per line"><textarea value={(profile.distinctive_outputs||[]).join("\n")} onChange={e=>update("distinctive_outputs",e.target.value.split("\n").map(x=>x.trim()).filter(Boolean))} placeholder="Research paper\nPrototype\nDocumentary\nPublished article…"/></Field></article>

    <article className="panel importPanel"><div><span className="overline">AI IMPORT</span><h3>Paste the messy version.</h3><p>AI converts a résumé, transcript notes and mixed Chinese/English activity descriptions into the structured profile. AP/IB/A-level subjects are extracted individually. Planned items stay planned.</p></div><textarea value={importText} onChange={e=>setImportText(e.target.value)} placeholder="Paste applicant information here…"/><button className="solid" onClick={importProfile}>{loading==="import"?"AI analyzing…":"Import with AI"}</button></article>
  </section>
}

function CoursePanel({title,hint,add,children}){return <div className="courseSection"><div className="courseHead"><div><b>{title}</b><small>{hint}</small></div><button className="quiet" onClick={add}>Add subject</button></div>{children?.length?children:<Empty text={`No ${title.toLowerCase()} entered yet.`}/>}</div>}

function Colleges({profile,rows,predictions,plans,addSchool,track,setTrack,country,setCountry,tier,setTier,institution,setInstitution,query,setQuery,sort,setSort,run,loading,rankCap,setRankCap,lacEnabled,toggleLac,selected,openCollege,closeCollege}){
  const trackMeta={
    common20:{title:"U.S. Common App 20",desc:"Your main 20-school U.S. portfolio."},
    us_extra:{title:"U.S. outside Common App",desc:"Separate U.S. systems and applications."},
    uk:{title:"UK track",desc:"Course-specific UK recommendations with separate bands."},
    all:{title:"All modeled",desc:"Explore every modeled option."}
  }[track]||{};
  const total=track==="common20"?(predictions?.us_common_app_20?.length||0):track==="us_extra"?(predictions?.us_outside_common_app?.length||0):track==="uk"?(predictions?.uk_track?.length||0):(predictions?.schools?.length||0);
  const favorites=(profile?.school_preferences||[]).filter(x=>Number(x.interest)>=7.5).map(pref=>{
    const all=[...(predictions?.us_common_app_20||[]),...(predictions?.us_outside_common_app||[]),...(predictions?.uk_track||[]),...(predictions?.schools||[])];
    const row=all.find(x=>sameSchool(x.school,pref.school_name));
    const inCommon=(predictions?.us_common_app_20||[]).some(x=>sameSchool(x.school,pref.school_name));
    const location=row?.country==="uk"?"UK track":row&&!row.common_app?"U.S. outside Common App":row&&rankCap&&["National University","National Liberal Arts College"].includes(row.usnews_system)&&Number(row.usnews_2026)>Number(rankCap)?`outside T${rankCap} scope`:inCommon?"Common App 20":"not modeled for this major";
    return {...pref,row,location};
  });
  if(selected)return <CollegeDetail s={selected} profile={profile} saved={plans.some(p=>p.school_name===selected.school)} add={()=>addSchool(selected)} back={closeCollege}/>;
  return <section className="stack">
    <article className="panel trackPanel"><div className="trackTabs"><button className={track==="common20"?"active":""} onClick={()=>setTrack("common20")}>Common App 20</button><button className={track==="us_extra"?"active":""} onClick={()=>setTrack("us_extra")}>U.S. outside Common App</button><button className={track==="uk"?"active":""} onClick={()=>setTrack("uk")}>UK</button><button className={track==="all"?"active":""} onClick={()=>setTrack("all")}>All modeled</button></div><div className="trackIntro"><div><span className="overline">{trackMeta.title}</span><h3>{track==="common20"?`${total} / 20 recommended slots`:`${total} modeled options`}</h3></div><p>{trackMeta.desc}</p></div></article>
    <article className="panel collegeToolbar v28">
      <div className="toolbarPrimary"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search university or program"/><Field label="Sort by"><select value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">UniPath recommendation</option><option value="usnews">U.S. News rank</option><option value="qs">QS rank</option><option value="chance_high">Chance · high to low</option><option value="chance_low">Chance · low to high</option><option value="course_fit">Course fit</option><option value="project_fit">Project fit</option><option value="preference">My preference</option></select></Field><button className="solid" onClick={()=>run()}>{loading==="predict"?"AI analyzing…":"Refresh model"}</button></div>
      <div className="toolbarSecondary">{track==="all"?<select value={country} onChange={e=>setCountry(e.target.value)}><option value="all">All countries</option>{Object.entries(COUNTRY_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>:<span className="filterChip">{track==="uk"?"United Kingdom":"United States"}</span>}{track==="uk"?<span className="filterChip">UK bands</span>:<select value={tier} onChange={e=>setTier(e.target.value)}><option value="all">All tiers</option>{["Lottery","Super Reach","Reach","Target","Likely"].map(x=><option key={x}>{x}</option>)}</select>}{track!=="uk"&&<button type="button" className={`lacSwitch ${lacEnabled?"on":"off"}`} disabled={loading==="predict"} onClick={()=>toggleLac(!lacEnabled)}><span>Liberal arts</span><b>{lacEnabled?"Included":"Excluded"}</b></button>}{track!=="uk"&&lacEnabled&&<select value={institution} onChange={e=>setInstitution(e.target.value)}><option value="all">All institution types</option><option value="university">Universities only</option><option value="lac">Liberal arts only</option></select>}{track!=="uk"&&<select value={rankCap||"all"} onChange={e=>setRankCap(e.target.value==="all"?null:Number(e.target.value))}><option value="all">All U.S. ranks</option><option value="30">T30 by category</option><option value="35">T35 by category</option><option value="50">T50 by category</option><option value="75">T75 by category</option><option value="100">T100 by category</option></select>}</div>
      <small className="toolbarHint">U.S. News sorting is within each published category; National Universities and Liberal Arts Colleges are not treated as one combined ranking.</small>
    </article>
    {!predictions?<article className="panel"><Empty text="Complete your profile and run the model."/></article>:<><article className="modelNote concise"><b>Profile {predictions.list_calibration?.profile_score??"—"} · Frontier {predictions.list_calibration?.stable_band_score??"—"}</b><span>NU T20 slots {predictions.list_calibration?.aspirational_t20_slots??0} · NU T30 frontier {predictions.list_calibration?.frontier_t30_slots??0} · selected NU T30 {predictions.list_calibration?.selected_t30??0} · LAC {predictions.list_calibration?.lac_enabled===false?"off":`${predictions.list_calibration?.selected_liberal_arts_colleges??0} selected`}</span></article>{favorites.length>0&&<div className="preferenceTrace"><b>Preference trace</b>{favorites.slice(0,9).map((f,i)=><span key={`${f.school_name}-${i}`}><strong>{f.school_name}</strong> · {f.interest}/10 · {f.location}</span>)}</div>}{(predictions.warnings||[]).map((w,i)=><div className="notice" key={i}>{w}</div>)}{!rows.length?<article className="panel"><Empty text="No schools match the current filters."/></article>:<div className="collegeList">{rows.map(s=><CollegeRow key={`${track}-${s.school}-${s.program}`} s={s} saved={plans.some(p=>p.school_name===s.school)} add={()=>addSchool(s)} open={()=>openCollege(s)}/>)}</div>}</>}
  </section>
}

function rankText(v){return v==null?"—":String(v)}
function evidenceSummary(s){const project=(s.project_details||[])[0],course=(s.academic_details||[]).filter(x=>x.relevance>=.35).sort((a,b)=>(b.relevance||0)-(a.relevance||0))[0];if(project?.name)return `Strongest modeled evidence: ${project.name}.`;if(course?.subject)return `Strongest modeled course signal: ${course.subject}.`;return s.major_match==="direct"?"Direct modeled program match.":"Program fit needs verification."}
function CollegeRow({s,saved,add,open}){
  const hs=s.high_school_context;const usnLabel=s.usnews_system==="National Liberal Arts College"?"U.S. News LAC":s.usnews_system?.includes("Global")?"U.S. News Global":s.usnews_system?.includes("Engineering")?"U.S. News Eng.":"U.S. News";
  const badge=(s.display_tier||s.tier).replaceAll(" ","").toLowerCase();
  return <article className="collegeRow rich v27"><div className="collegeName"><b>{s.school}</b><span>{s.program} · {COUNTRY_LABEL[s.country]||s.country}</span><div className="badges"><i className={`tier ${badge}`}>{s.display_tier||s.tier}</i>{s.institution_type==="liberal_arts_college"&&<i className="context">Liberal arts</i>}{s.major_match!=="direct"&&<i className="context">{s.major_match==="adjacent"?"Adjacent field":"Verify program"}</i>}{hs?.label&&<i className="context">School context</i>}</div></div><div className="chance"><b>{pct(s.interval[0])}–{pct(s.interval[1])}</b><div className="rankStrip"><span><i>QS</i><strong>{rankText(s.qs_2026)}</strong></span><span><i>{usnLabel}</i><strong>{rankText(s.usnews_2026)}</strong></span></div></div><div className="why compactWhy"><div className="fitStrip"><span><i>Courses</i><b>{score(s.academic_fit)}</b></span><span><i>Projects</i><b>{score(s.project_fit)}</b></span><span><i>Interdisc.</i><b>{score(s.interdisciplinary_fit)}</b></span></div><small>{evidenceSummary(s)}</small></div><div className="collegeActions"><button className="quiet" onClick={open}>Details</button><button className={saved?"saved":"quiet"} disabled={saved} onClick={add}>{saved?"Saved":"Save"}</button></div></article>
}
function fallbackSchoolInsight(s,catalog={}){
  const lac=s.institution_type==="liberal_arts_college";const research=Number(catalog.research)||0;const urban=!!catalog.urban;const direct=s.major_match==="direct";
  const field=s.major_category||"academic";
  const values=lac?["Sustained intellectual engagement","Contribution to a small learning community","Independent thinking and discussion","Depth rather than activity accumulation"]:[research>=9?"Using a research-rich environment with initiative":"Strong academic preparation",urban?"Connecting learning to an external community":"Meaningful campus contribution",direct?"Clear program-level academic fit":"A credible interdisciplinary path","Evidence of follow-through and impact"];
  return {signature:lac?`${s.school} is modeled here as an undergraduate-centered liberal arts environment; for ${s.program}, UniPath therefore tests intellectual depth, faculty-facing work and contribution to a close learning community.`:`${s.school} is modeled as a ${research>=9?"research-intensive":"broad"} university${urban?" in an urban setting":""}; the strongest ${s.program} case needs evidence that the student would use that environment rather than simply admire it.`,values:[...values.slice(0,3),direct?`Executed evidence aligned with ${s.program}`:`A credible bridge into ${s.program}`],application_read:`For ${s.school}, this profile should be read through the combination of ${direct?"direct program preparation":"an adjacent academic route"}, executed work, and contribution beyond grades. This fallback is an UniPath fit interpretation, not a claim about an unpublished institutional rubric.`,positioning:`Lead with the strongest course and project evidence for ${s.program} at ${s.school}. ${urban?"If relevant, show how the surrounding city or community expands work you already do.":"Show how you would turn campus resources and faculty access into concrete work."}`,avoid:`Generic prestige language, rankings as a reason for choosing ${s.school}, or repeating the same Why School argument used elsewhere.`,student_voice:lac?`For ${s.school}, UniPath's fallback emphasizes the implications of a small-college environment—discussion, faculty access and community contribution—without claiming those are official selection criteria.`:research>=9?`Because ${s.school} is research-heavy in the catalog, the fallback fit story rewards curiosity, initiative and real follow-through rather than merely wanting access to famous resources.`:`For ${s.school}, the fallback fit story connects academic preparation with a concrete way of participating in the campus community.`,sources:[]};
}

function CollegeDetail({s,profile,saved,add,back}){
  const courses=(s.academic_details||[]).filter(x=>x.relevance>=.25).sort((a,b)=>(b.relevance||0)-(a.relevance||0)).slice(0,8),projects=(s.project_details||[]).slice(0,6),rules=roundRules[s.school]||{plans:[s.country==="uk"?"UCAS":"RD"]};
  const usnLabel=s.usnews_system==="National Liberal Arts College"?"U.S. News Liberal Arts 2026":s.usnews_system?.includes("Global")?"U.S. News Global 2026–27":"U.S. News 2026";
  const catalog=schools.find(x=>sameSchool(x.name,s.school))||{};const lac=s.institution_type==="liberal_arts_college";const sourced=schoolInsights[s.school];
  const insight=sourced||fallbackSchoolInsight(s,catalog);
  const topProject=projects[0]?.name,topCourse=courses[0]?.subject,preference=(profile?.school_preferences||[]).find(x=>sameSchool(x.school_name,s.school));
  return <section className="stack collegeDetailPage v28">
    <article className="panel detailHero schoolDetailHero"><div><button className="textButton detailBack" onClick={back}>← Back to colleges</button><span className="overline">COLLEGE DETAIL · SCHOOL-SPECIFIC READ</span><h2>{s.school}</h2><p>{s.program} · {COUNTRY_LABEL[s.country]||s.country}</p><div className="badges"><i className={`tier ${(s.display_tier||s.tier).replaceAll(" ","").toLowerCase()}`}>{s.display_tier||s.tier}</i>{lac&&<i className="context">Liberal arts college</i>}<i className="context">{s.major_match==="direct"?"Direct program fit":s.major_match==="adjacent"?"Adjacent field":"Program verification needed"}</i>{preference&&<i className="context">Your interest {preference.interest}/10</i>}</div><p className="schoolSignature">{insight.signature}</p></div><div className="detailChance"><span>Planning interval</span><strong>{pct(s.interval[0])}–{pct(s.interval[1])}</strong><small>center {pct(s.probability)}</small><button className={saved?"saved":"solid"} disabled={saved} onClick={add}>{saved?"Saved to applications":"Save school"}</button></div></article>
    <section className="detailMetrics"><Metric label="Course fit" value={score(s.academic_fit)}/><Metric label="Project fit" value={score(s.project_fit)}/><Metric label="Interdisciplinary" value={score(s.interdisciplinary_fit)}/><Metric label="Profile signal" value={score(s.profile_score)}/></section>
    <section className="detailGrid schoolReadGrid"><article className="panel schoolDNA"><span className="overline">WHAT THIS SCHOOL APPEARS TO VALUE</span><h3>A school-specific admissions lens</h3><div className="valueGrid">{(insight.values||[]).map((x,i)=><div className="valueCard" key={i}><span>0{i+1}</span><b>{x}</b></div>)}</div><p>{insight.application_read}</p></article><article className="panel"><span className="overline">YOUR POSITIONING</span><h3>How this profile could read here</h3><p>{insight.positioning}</p><div className="personalRead">{topProject&&<span><b>Lead project evidence</b>{topProject}</span>}{topCourse&&<span><b>Lead course evidence</b>{topCourse}</span>}<span><b>Do not default to</b>{insight.avoid}</span></div></article></section>
    <section className="detailGrid"><article className="panel"><span className="overline">WHY IT FITS</span><h3>Evidence behind the recommendation</h3><div className="detailEvidence"><div><b>Course evidence</b>{courses.length?courses.map((c,i)=><span key={i}>{c.subject}<i>{c.type?.toUpperCase()} · relevance {Math.round((c.relevance||0)*100)}% · evidence {Math.round(c.achievement||0)}</i></span>):<span>No detailed course evidence entered.</span>}</div><div><b>Project evidence</b>{projects.length?projects.map((x,i)=><span key={i}>{x.name}<i>{(x.evidence||[]).slice(0,4).join(" · ")||"Activity evidence detected"}</i></span>):<span>No executed project detail detected.</span>}</div></div></article><article className="panel"><span className="overline">RISKS & GAPS</span><h3>What could weaken this application</h3><div className="gapList">{(s.academic_gaps||[]).slice(0,4).map((x,i)=><span key={`a-${i}`}>Academic · {x}</span>)}{(s.project_gaps||[]).slice(0,4).map((x,i)=><span key={`p-${i}`}>Project · {x}</span>)}{!(s.academic_gaps||[]).length&&!(s.project_gaps||[]).length&&<span>No major evidence gap flagged by the current model.</span>}</div>{s.interdisciplinary_note&&<div className="contextCallout"><b>Interdisciplinary read</b><span>{s.interdisciplinary_note}</span></div>}</article></section>
    <section className="detailGrid lower"><article className="panel"><span className="overline">CULTURE / STUDENT VOICE</span><h3>What the institution says about its community</h3><p>{insight.student_voice}</p><div className="contextCallout"><b>Use this correctly</b><span>Translate these themes into specific evidence from your own work. Do not copy institutional language into an essay or manufacture a personality to match it.</span></div></article><article className="panel"><span className="overline">RANKING & ROUNDS</span><h3>Reference information</h3><div className="detailStatRows"><span><b>QS 2026</b><i>{rankText(s.qs_2026)}</i></span><span><b>{usnLabel}</b><i>{rankText(s.usnews_2026)}</i></span><span><b>Modeled rounds</b><i>{(rules.plans||[rules.default||"RD"]).map(r=>roundLabel[r]||r).join(" · ")}</i></span><span><b>Institution</b><i>{lac?"Liberal Arts College":"University"}</i></span></div></article></section>
    <section className="detailGrid lower"><article className="panel"><span className="overline">ADMISSIONS CONTEXT</span><h3>How to read the number</h3><div className="detailStatRows"><span><b>Modeled center</b><i>{pct(s.probability)}</i></span><span><b>Planning range</b><i>{pct(s.interval[0])}–{pct(s.interval[1])}</i></span><span><b>Data quality</b><i>{s.data_quality||"seed"}</i></span><span><b>Application system</b><i>{s.common_app?"Common App":"Separate / verify"}</i></span></div><p>The probability interval is a planning estimate. The school-specific content above changes how UniPath explains fit and positioning; it does not secretly inflate the probability.</p></article><article className="panel"><span className="overline">RESEARCH SOURCES</span><h3>{sourced?"Sources behind this school profile":"Dynamic profile from UniPath catalog"}</h3>{sourced?<div className="sourceLinks">{(insight.sources||[]).map((x,i)=><a key={i} href={x.url} target="_blank" rel="noreferrer"><span>{x.type==="official"?"Official":"Institutional voice"}</span><b>{x.label}</b><i>↗</i></a>)}</div>:<p>This school does not yet have a hand-researched admissions profile in v2.8. UniPath varies the detail using institution type, research intensity, setting, program support and your evidence instead of displaying a generic copied template.</p>}</article></section>
  </section>
}

function Opportunities({items,saved,kind,setKind,query,setQuery,search,save,remove,loading,generated,generateProjects,addProject,selectedProject,openProject,closeProject}){
  const savedIds=new Set(saved.map(x=>x.opportunity_id));const projects=generated?.projects||[];
  if(selectedProject)return <ProjectDetail project={selectedProject} addProject={()=>addProject(selectedProject)} back={closeProject} loading={loading}/>;
  return <section className="stack"><article className="panel opportunityHero"><div><span className="overline">CURATED + ORIGINAL</span><h2>Use programs when they fit. Build your own work when they do not.</h2><p>The catalog matches external opportunities. Original projects are built around your current gaps, and each draft now opens into a full execution and application-impact plan.</p></div><button className="solid" onClick={generateProjects}>{loading==="projects"?"AI analyzing…":"Generate original projects"}</button></article>{projects.length>0&&<article className="panel generated projectDraftPanel"><div className="panelHead"><div><span className="overline">CUSTOM PROJECT DRAFTS</span><h3>{generated.summary||"Projects built around your current gaps"}</h3></div></div><div className="projectGrid v28">{projects.map((p,i)=><article className="projectCard compactProject" key={`${p.title}-${i}`}><div className="projectMeta"><span>{p.duration_weeks||8} weeks</span><span>{p.hours_per_week||3} h/week</span><span>{p.difficulty||"medium"}</span></div><h3>{p.title}</h3><p>{p.why_this_student}</p><div className="tags">{(p.gaps_addressed||[]).slice(0,3).map(x=><span key={x}>{x}</span>)}</div><div className="projectSignal"><span>Application role</span><b>{p.admissions_impact?.primary_signal||deriveProjectImpact(p).primary_signal}</b></div><div className="projectCardActions"><button className="quiet" onClick={()=>openProject(p)}>View full plan</button><button className="textButton" onClick={()=>addProject(p)}>Add to roadmap</button></div></article>)}</div></article>}<article className="panel filterBar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search summer, research, competition or project"/><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All pathways</option>{["summer","research","competition","project","work"].map(x=><option key={x}>{x}</option>)}</select><button className="solid" onClick={search}>{loading==="opps"?"Matching…":"Match catalog to profile"}</button></article><article className="modelNote"><b>Opportunity catalog</b><span>Match prioritizes field relevance, eligibility and missing evidence—not brand name alone. Verify current deadlines and requirements at the official source before applying.</span></article><div className="oppGrid">{items.map(o=><article className="opp" key={o.id}><div className="oppTop"><span className="kind">{o.kind}</span><b>{o.match_score}</b></div><h3>{o.name}</h3><p>{o.provider}</p><div className="tags">{o.tags.slice(0,4).map(t=><span key={t}>{t}</span>)}</div><ul>{(o.match_reasons||[]).map(r=><li key={r}>{r}</li>)}</ul><div className="oppFoot"><span>{o.selectivity} · {o.cost}</span>{savedIds.has(o.id)?<button onClick={()=>remove(o)}>Saved ✓</button>:<button onClick={()=>save(o)}>Save</button>}</div></article>)}</div></section>
}

function deriveProjectImpact(project){
  const gaps=(project.gaps_addressed||[]).slice(0,3);const outputs=(project.deliverables||[]).slice(0,3);
  return {primary_signal:gaps[0]?`Builds evidence in ${gaps[0]}`:"Turns an interest into executed evidence",why_it_matters:`The project matters only if the work is completed and documented. Its strongest admissions value is showing a chain from question → method → output → reflection, rather than adding another activity label.`,secondary_signals:[...gaps.slice(1),outputs[0]&&`Produces ${outputs[0]}`].filter(Boolean),application_uses:["Activities section: concise evidence of responsibility, method and output","Supplemental essays: context only when the project genuinely answers the prompt","Portfolio / additional information: link or describe a finished artifact when the college accepts it","Recommendation context: useful only if a teacher or mentor actually observed the work"]};
}
function ProjectDetail({project,addProject,back,loading}){
  const impact={...deriveProjectImpact(project),...(project.admissions_impact||{})};const milestones=(project.milestones||[]).length?project.milestones:(project.steps||[]).map((x,i)=>({week:`Phase ${i+1}`,goal:x,proof:(project.deliverables||[])[Math.min(i,(project.deliverables||[]).length-1)]||"Document the completed work"}));
  return <section className="stack projectDetailPage"><article className="panel projectDetailHero"><div><button className="textButton detailBack" onClick={back}>← Back to projects</button><span className="overline">ORIGINAL PROJECT · EXECUTION PLAN</span><h2>{project.title}</h2><p>{project.why_this_student}</p><div className="projectMeta large"><span>{project.duration_weeks||8} weeks</span><span>{project.hours_per_week||3} h/week</span><span>{project.difficulty||"medium"}</span></div></div><button className="solid" onClick={addProject}>{loading==="addProject"?"Saving…":"Add project to roadmap"}</button></article>
    <section className="projectImpactGrid"><article className="panel impactLead"><span className="overline">ROLE IN THE APPLICATION</span><h3>{impact.primary_signal}</h3><p>{impact.why_it_matters}</p><div className="signalChips">{(impact.secondary_signals||[]).map((x,i)=><span key={i}>{x}</span>)}</div></article><article className="panel"><span className="overline">WHAT IT FIXES</span><div className="gapList">{(project.gaps_addressed||[]).map((x,i)=><span key={i}>{x}</span>)}{!(project.gaps_addressed||[]).length&&<span>No explicit gap returned; treat this as a depth-building project.</span>}</div><span className="overline sectionOverline">BUILDS ON</span><div className="gapList compact">{(project.build_on||[]).map((x,i)=><span key={i}>{x}</span>)}</div></article></section>
    <article className="panel"><span className="overline">MILESTONES</span><h3>Turn the idea into proof of execution</h3><div className="milestoneList">{milestones.map((m,i)=><div className="milestone" key={i}><span>{m.week||`Phase ${i+1}`}</span><div><b>{m.goal||m}</b>{m.proof&&<small>Evidence to keep · {m.proof}</small>}</div></div>)}</div></article>
    <section className="projectColumns"><article className="panel"><span className="overline">DELIVERABLES</span><h3>What must exist at the end</h3><ul className="cleanList">{(project.deliverables||[]).map((x,i)=><li key={i}>{x}</li>)}</ul></article><article className="panel"><span className="overline">SUCCESS METRICS</span><h3>How to know it became substantial</h3><ul className="cleanList">{(project.success_metrics||[]).map((x,i)=><li key={i}>{x}</li>)}</ul></article><article className="panel"><span className="overline">EXTERNAL VALIDATION</span><h3>Optional proof beyond yourself</h3><ul className="cleanList">{(project.external_validation||[]).map((x,i)=><li key={i}>{x}</li>)}</ul></article></section>
    <section className="detailGrid lower"><article className="panel"><span className="overline">APPLICATION USES</span><h3>Where this work may become relevant</h3><ul className="cleanList">{(impact.application_uses||[]).map((x,i)=><li key={i}>{x}</li>)}</ul><div className="contextCallout"><b>Important</b><span>The project should exist because the question and work are worth doing. UniPath maps completed evidence to an application; it should not turn an unfinished idea into a claimed achievement.</span></div></article><article className="panel"><span className="overline">RESOURCES & RISKS</span><h3>Plan around constraints before you start</h3><ul className="cleanList">{(project.resources||["A clear research / design log","Versioned data, drafts or prototypes","A realistic advisor or peer feedback loop"]).map((x,i)=><li key={`r-${i}`}>{x}</li>)}</ul>{(project.risks||[]).length>0&&<><span className="overline sectionOverline">RISKS</span><ul className="cleanList">{project.risks.map((x,i)=><li key={`risk-${i}`}>{x}</li>)}</ul></>}</article></section>
  </section>
}

function Roadmap({profile,items,generated,generate,accept,update,remove,clearStale,savedOpps,loading}){const currentMonth=new Date().toISOString().slice(0,7);const stale=items.filter(x=>x.status!=="done"&&x.due_window&&x.due_window<currentMonth).length;return <section className="stack"><article className="panel roadmapHero"><div><span className="overline">LIVING PLAN</span><h2>Turn the profile into the next 9–12 months.</h2><p>Dates are anchored to today and graduation year <b>{profile?.graduation_year||"not set"}</b>. The roadmap is persistent. The advisor sees it, and future recommendations can build on what you finished instead of restarting every conversation.</p></div><div className="row">{stale>0&&<button className="quiet" onClick={clearStale}>{loading==="clearStale"?"Cleaning…":`Remove ${stale} past-dated open item${stale>1?"s":""}`}</button>}<button className="solid" onClick={generate}>{loading==="roadmap"?"AI planning…":"Generate roadmap"}</button></div></article>{generated&&<article className="panel generated"><div className="panelHead"><div><span className="overline">AI DRAFT</span><h3>{generated.summary||"Roadmap draft"}</h3></div><button className="solid" onClick={accept}>{loading==="acceptRoadmap"?"Saving…":"Add to my roadmap"}</button></div><div className="roadmapList">{(generated.items||[]).map((x,i)=><div className="roadItem" key={i}><span className={`priority ${x.priority}`}>{x.priority}</span><div><b>{x.title}</b><small>{x.due_window} · {x.why}</small><em>{x.success_metric}</em></div></div>)}</div></article>}
    <article className="panel"><div className="panelHead"><div><span className="overline">MY ROADMAP</span><h3>{items.length} active records</h3></div><span className="muted">{savedOpps.length} opportunities saved</span></div>{!items.length?<Empty text="No roadmap items yet. Generate a draft or add opportunities first."/>:<div className="roadmapList">{items.map(x=><div className={`roadItem ${x.status==="done"?"done":""}`} key={x.id}><button className="checkBtn" onClick={()=>update(x,{status:x.status==="done"?"todo":"done"})}>{x.status==="done"?"✓":"○"}</button><div><b>{x.title}</b><small>{x.due_window||x.due_date||"No date"} · {x.why||x.item_type}</small>{x.success_metric&&<em>{x.success_metric}</em>}</div><span className={`priority ${x.priority}`}>{x.priority}</span><button className="iconDanger" onClick={()=>remove(x)}>×</button></div>)}</div>}</article></section>}

function Applications({predictions,plans,draftPlans,effectivePlans,saveDraft,change,remove,strategy,simulate,simulation,loading}){
  const auto=predictions?.round_strategy||strategy?.strategy||null;
  const common=auto?.recommended_plan||[];
  const outside=auto?.outside_common_app_plan||[];
  const modelPlan=draftPlans||[];
  const group=(rounds,source=common)=>source.filter(x=>rounds.includes(x.round));
  const ed1=auto?.ed1,ed2=auto?.ed2,restrictive=auto?.restrictive_option;
  const route=auto?.route||"nonbinding_early";
  const roundName=r=>roundLabel[r]||r;
  const shape=(predictions?.us_common_app_20||[]).reduce((acc,x)=>{acc[x.tier]=(acc[x.tier]||0)+1;return acc},{});
  const cycle=simulation?.example_cycle||simulation?.simulation?.visible_cycle||null;
  return <section className="stack">
    <article className="panel strategyHero">
      <div><span className="overline">AUTOMATIC ROUND PLAN</span><h2>{route==="binding_ed"&&ed1?`ED I → ${ed1.school}`:route==="restrictive_early"&&restrictive?`${restrictive.plan} → ${restrictive.school}`:"Non-binding early route"}</h2><p>UniPath generates this from the latest profile + 20-school U.S. recommendation set. Saving a college is optional persistence; it is not required for ED/EA/RD recommendations to appear.</p></div><div className="row"><button className="quiet" disabled={!modelPlan.length} onClick={()=>saveDraft(modelPlan)}>{loading==="saveDraft"?"Saving…":"Save model plan"}</button><button className="solid" disabled={!modelPlan.length} onClick={()=>simulate(3000,modelPlan)}>{loading==="simulate"?"Simulating…":"Simulate model plan"}</button></div>
    </article>

    {!auto?<article className="panel"><Empty text="Run the College model first. ED/EA/RD strategy is generated automatically from that prediction; you do not need to add schools manually."/></article>:<>
      <article className="panel strategyPanel"><div className="panelHead"><div><span className="overline">EARLY DECISION</span><h3>One recommended route, not a menu of random reaches</h3></div><span className="muted">Binding choices require genuine preference + affordability</span></div><div className="strategyGrid threeStrategy">
        <div className={`strategyCard ${route==="binding_ed"?"selected":""}`}><span>Recommended ED I</span><b>{ed1?.school||"No binding ED I recommended"}</b><small>{ed1?.rationale||"The model did not find an ED I option strong enough to justify a binding recommendation from the current list."}</small></div>
        <div className="strategyCard"><span>Conditional ED II</span><b>{ed2?.school||"—"}</b><small>{ed2?.rationale||"No ED II contingency in the current model plan. ED II is never treated as simultaneous with ED I."}</small></div>
        <div className={`strategyCard ${route==="restrictive_early"?"selected":""}`}><span>Restrictive alternative</span><b>{restrictive?`${restrictive.plan} · ${restrictive.school}`:"—"}</b><small>{restrictive?.rationale||"No REA/SCEA alternative is currently preferred over the binding route."}</small></div>
      </div><div className="notice">ED/REA/SCEA policy logic changes by university and cycle. UniPath organizes a strategy; it does not override the university's current official rules.</div></article>

      <article className="panel"><div className="panelHead"><div><span className="overline">COMMON APP</span><h3>{common.length} / 20 U.S. Common App slots</h3></div><div className="portfolioShape"><span><b>{(shape.Lottery||0)+(shape["Super Reach"]||0)}</b> ultra-high risk</span><span><b>{shape.Reach||0}</b> reach</span><span><b>{shape.Target||0}</b> target</span><span><b>{shape.Likely||0}</b> likely</span></div></div>{common.length!==20&&<div className="error">The model should produce exactly 20 Common App recommendations. Current output: {common.length}. Refresh the model; if this repeats, treat it as a catalog bug.</div>}<div className="roundGroups">
        {[{title:"ED / ED II",rounds:["ED1","ED2"]},{title:"EA / EA2",rounds:["EA","EA2"]},{title:"RD",rounds:["RD"]}].map(g=><div className="roundGroup" key={g.title}><span>{g.title}</span>{group(g.rounds).length?group(g.rounds).map(x=><div className="roundSchool" key={`${x.school_name}-${x.round}`}><div><b>{x.school_name}</b><small>{x.program}</small>{x.round_reason&&<em>{x.round_reason}</em>}</div><i>{roundName(x.round)}</i></div>):<small className="muted">None in this group.</small>}</div>)}
      </div></article>

      <article className="panel"><div className="panelHead"><div><span className="overline">OUTSIDE THE 20 COMMON APP SLOTS</span><h3>Separate U.S. systems / applications</h3></div><span className="muted">Does not replace a Common App slot in this planner</span></div>{outside.length?<div className="applicationList">{outside.map(x=><div className="appRow" key={`${x.school_name}-${x.round}`}><div><b>{x.school_name}</b><span>{x.program}</span></div><span>{pct(x.probability_min)}–{pct(x.probability_max)}</span><span className="roundPill">{roundName(x.round)}</span><span/></div>)}</div>:<Empty text="No outside-Common-App U.S. recommendations in the current model output."/>}</article>

      <article className="panel"><div className="panelHead"><div><span className="overline">SAVED OVERRIDES</span><h3>{plans.length} manually saved applications</h3></div>{plans.length>0&&<button className="quiet" onClick={()=>simulate(3000,plans)}>{loading==="simulate"?"Simulating…":"Simulate my saved version"}</button>}</div><p className="muted">These are editable user overrides. They do not control whether the automatic model can generate ED/EA/RD strategy.</p>{!plans.length?<Empty text="Nothing saved yet. That is fine—the automatic plan above remains fully available."/>:<div className="applicationList">{plans.map(p=>{const rules=roundRules[p.school_name]||{plans:[p.country==="uk"?"UCAS":"RD"]};return <div className="appRow" key={p.id}><div><b>{p.school_name}</b><span>{p.program}</span></div><span>{pct(p.probability_min)}–{pct(p.probability_max)}</span><select value={p.round} onChange={e=>change(p,{round:e.target.value})}>{rules.plans.map(r=><option key={r} value={r}>{roundName(r)}</option>)}</select><button className="iconDanger" onClick={()=>remove(p)}>×</button></div>})}</div>}</article>
    </>}

    <article className="panel"><div className="panelHead"><div><span className="overline">MONTE CARLO</span><h3>Portfolio risk + one visible simulated cycle</h3></div></div>{simulation?<><div className="metricRow compact five"><Metric label="Expected admits" value={simulation.simulation.expected_admits.toFixed(1)}/><Metric label="Zero-admit risk" value={pct(simulation.simulation.zero_admit_risk)}/><Metric label="Binding finish" value={pct(simulation.simulation.binding_finish_rate)}/><Metric label="T20-category hit" value={pct(simulation.simulation.top20_hit_rate)}/><Metric label="T30-category hit" value={pct(simulation.simulation.top30_hit_rate)}/></div>{cycle?.results?.length?<div className="cycleResult"><span className="overline">ONE SIMULATED CYCLE</span>{cycle.results.map((r,i)=><div className="cycleRow" key={`${r.school_name}-${i}`}><div><b>{r.school_name}</b><small>{roundName(r.round)} · {r.note}</small></div><strong className={`outcome ${String(r.outcome).toLowerCase().replace(/[^a-z]/g,"")}`}>{r.outcome}</strong></div>)}</div>:<Empty text="The aggregate simulation ran, but no visible example cycle was returned."/>}</>:<Empty text={modelPlan.length?"Run the model-plan simulation after reviewing the automatic round assignments.":"Run a college prediction before simulating."}/>}</article>
  </section>
}
function Advisor({chat,question,setQuestion,send,clear,loading}){return <section className="advisorLayout"><article className="panel advisorPanel"><div className="panelHead"><div><span className="overline">PERSISTENT THREAD</span><h3>Your strategy conversation</h3></div><div className="row"><span className="chatSync">Account-synced</span><button className="textButton" onClick={clear}>Clear</button></div></div><div className="chat">{chat.length?chat.map((m,i)=><div className={`message ${m.role}${m.error?" error":""}`} key={m.id||`${m.client_id||"m"}-${i}`}>{m.text}</div>):<div className="message ai">I can use your saved profile, current prediction intervals, application plan and roadmap. Ask a question that changes a decision.</div>}</div><div className="composer"><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="What should I prioritize next?"/><button className="solid" disabled={loading==="chat"} onClick={send}>{loading==="chat"?"Thinking…":"Send"}</button></div></article><aside className="panel prompts"><span className="overline">USEFUL QUESTIONS</span>{["我的活动现在最像什么申请叙事？","未来六个月最值得完成的三个输出是什么？","我的选校是不是过于激进？","如果不参加昂贵夏校，我该怎么补强？","第二专业到底有没有真实战略价值？"].map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}</button>)}</aside></section>}

function History({rows}){return <article className="panel"><span className="overline">MODEL HISTORY</span>{!rows.length?<Empty text="No prediction history yet."/>:<div className="history">{rows.map(r=><div key={r.id}><b>{r.primary_major||"Unknown major"}</b><span>{new Date(r.created_at).toLocaleString()}</span><small>{r.result?.ai_status==="cached"?"AI cache reused":r.result?.ai_status==="fallback"?"AI fallback":"Model run"} · {r.result?.schools?.length||0} schools</small></div>)}</div>}</article>}
function Settings({language,setLanguage,density,setDensity,theme,setTheme,profile,setProfile,saveProfile,restartOnboarding}){
  const cap=profile.us_rank_cap==null?"all":profile.us_rank_cap,lac=profile.include_liberal_arts_colleges!==false;
  return <section className="stack"><article className="panel"><span className="overline">GENERAL</span><h3>Interface & recommendation preferences</h3><div className="formGrid settingsGrid"><Field label="Language"><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="zh">简体中文</option></select></Field><Field label="Appearance"><div className="segmented">{[["system","System"],["light","Light"],["dark","Dark"]].map(([v,label])=><button type="button" key={v} className={theme===v?"active":""} onClick={()=>setTheme(v)}>{label}</button>)}</div></Field><Field label="Density"><select value={density} onChange={e=>setDensity(e.target.value)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></Field><Field label="U.S. ranking scope"><select value={cap} onChange={e=>setProfile(p=>({...p,us_rank_cap:e.target.value==="all"?null:Number(e.target.value)}))}><option value="all">All modeled U.S. schools</option><option value="30">T30 by category</option><option value="35">T35 by category</option><option value="50">T50 by category</option><option value="75">T75 by category</option><option value="100">T100 by category</option></select></Field><Field label="Liberal arts colleges"><div className="segmented twoSegment"><button type="button" className={lac?"active":""} onClick={()=>setProfile(p=>({...p,include_liberal_arts_colleges:true}))}>Include</button><button type="button" className={!lac?"active":""} onClick={()=>setProfile(p=>({...p,include_liberal_arts_colleges:false}))}>Exclude</button></div></Field></div><div className="row settingsActions"><button className="solid" onClick={saveProfile}>Save settings</button></div></article><article className="panel"><div className="panelHead"><div><span className="overline">ACCOUNT & GUIDANCE</span><h3>Session behavior</h3></div><button className="quiet" onClick={restartOnboarding}>Replay first-use guide</button></div><p>Authentication persists your session. Advisor conversations are account-synced and mirrored locally. You can replay the onboarding guide at any time without changing your profile or predictions.</p></article></section>
}

function Onboarding({language,step,setStep,finish}){
  const zh=language==="zh";const steps=zh?[{k:"01",title:"一个档案，驱动整个系统",text:"先把课程、成绩、活动、项目、奖项和偏好放进 Profile。后面的选校、项目和 Roadmap 都会使用同一份档案。",action:"profile"},{k:"02",title:"先看推荐，再看排名",text:"College Model 先按你的竞争力和专业生成组合。之后你可以按 U.S. News、QS、录取区间或 fit 排序，也可以关闭文理学院。",action:"colleges"},{k:"03",title:"项目必须落到执行",text:"原创项目不是四张建议卡。点进每个项目可以看到里程碑、产出、验证方式，以及它在申请里真正补什么证据。",action:"opportunities"},{k:"04",title:"规划会继续，不会每次重来",text:"Roadmap 与 AI Advisor 会读取已保存的档案和历史。聊天内容同步到账号，并保留最近的本地恢复副本。",action:"advisor"}]:[{k:"01",title:"One profile powers the system",text:"Start with courses, grades, activities, projects, awards and preferences. College modeling, projects and the roadmap all reuse the same profile.",action:"profile"},{k:"02",title:"Recommendation first, ranking second",text:"The College Model builds a portfolio from fit and competitiveness. Then sort by U.S. News, QS, probability or fit, and include or exclude liberal arts colleges.",action:"colleges"},{k:"03",title:"A project needs an execution plan",text:"Open every original project to see milestones, deliverables, validation and the exact evidence it is meant to add to the application.",action:"opportunities"},{k:"04",title:"Your plan continues",text:"Roadmap and Advisor reuse saved context. Advisor messages sync to your account and keep a recent local recovery copy.",action:"advisor"}];const current=steps[Math.min(step,steps.length-1)];
  return <div className="onboardingBackdrop" role="dialog" aria-modal="true"><article className="onboardingCard"><div className="onboardingTop"><div><span className="overline">FIRST USE · {current.k} / 04</span><h2>{current.title}</h2></div><button className="textButton" onClick={()=>finish(null)}>{zh?"跳过":"Skip"}</button></div><p>{current.text}</p><div className="onboardingPreview"><div className={`guideIcon guide${step+1}`}>{current.k}</div><div><b>{zh?"你现在需要知道的":"What matters now"}</b><span>{step===0?(zh?"先完成 Profile，再运行一次模型。":"Complete Profile, then run the model once."):step===1?(zh?"排序只改变查看顺序，不会改变录取概率。":"Sorting changes the view, not the probability model."):step===2?(zh?"只有完成的项目和可验证产出才算申请证据。":"Only executed work and verifiable outputs become evidence."):(zh?"离开页面后回来，历史仍应存在。":"Leave the page and return; the history should remain.")}</span></div></div><div className="onboardingProgress">{steps.map((_,i)=><button key={i} className={i===step?"active":i<step?"done":""} onClick={()=>setStep(i)} aria-label={`Step ${i+1}`}/>)}</div><div className="onboardingActions"><button className="quiet" disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}>{zh?"上一步":"Back"}</button>{step<steps.length-1?<button className="solid" onClick={()=>setStep(step+1)}>{zh?"下一步":"Next"}</button>:<button className="solid" onClick={()=>finish("profile")}>{zh?"开始完善档案":"Start with Profile"}</button>}</div></article></div>
}

function Admin({data,school,setSchool,json,setJson,save,demoPassword,setDemoPassword,demoAccounts,seedDemo,loading}){
  if(!data)return <article className="panel"><Empty text="Loading admin data…"/></article>;
  return <section className="stack"><section className="metricRow"><Metric label="Profiles" value={data.stats.profiles}/><Metric label="Prediction runs" value={data.stats.runs}/><Metric label="Roadmap items" value={data.stats.roadmap}/><Metric label="Chat messages" value={data.stats.chat}/></section><article className="two"><div className="panel"><span className="overline">INFRASTRUCTURE</span><h3>AI + Supabase</h3><p>{data.catalog?.universities} universities · {data.catalog?.high_schools} high schools · {data.catalog?.total} curated opportunity pathways.</p><div className="notice">Keep the AI provider key and the Supabase server key server-only in Vercel.</div></div><div className="panel"><span className="overline">UNIVERSITY DATA OVERRIDE</span><select value={school} onChange={e=>setSchool(e.target.value)}>{schools.map(s=><option key={s.name}>{s.name}</option>)}</select><textarea className="code" value={json} onChange={e=>setJson(e.target.value)}/><button className="solid" onClick={save}>Save verified override</button></div></article><article className="panel"><div className="panelHead"><div><span className="overline">CLASSMATE TEST ACCOUNTS</span><h3>Create 5 ordinary non-admin demo users</h3></div></div><p>Choose a shared temporary password. The server creates or resets five isolated Supabase users. Their credentials are not hard-coded in the public repository.</p><div className="demoSeed"><input type="password" value={demoPassword} onChange={e=>setDemoPassword(e.target.value)} placeholder="Temporary password · 10+ characters"/><button className="solid" onClick={seedDemo}>{loading==="demo"?"Creating…":"Create / reset demo accounts"}</button></div>{demoAccounts.length>0&&<div className="demoAccounts">{demoAccounts.map(a=><div key={a.email}><b>{a.email}</b><code>{a.password||a.status}</code></div>)}</div>}<div className="notice">These accounts can use normal user features and are not admins. Because they can trigger paid AI requests, remove or reset them after the testing period.</div></article><article className="panel"><span className="overline">ACTIVE OVERRIDES</span>{data.overrides?.length?data.overrides.map(o=><div className="override" key={o.school_name}><b>{o.school_name}</b><code>{JSON.stringify(o.data)}</code></div>):<Empty text="No live university overrides."/>}</article></section>
}

function Metric({label,value}){return <div className="metric"><span>{label}</span><b>{value}</b></div>}
function Mini({label,value}){return <div className="mini"><span>{label}</span><b>{value}</b></div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Empty({text}){return <div className="empty">{text}</div>}
function ActionLine({n,title,text,onClick}){return <button className="actionLine" onClick={onClick}><span>{n}</span><div><b>{title}</b><small>{text}</small></div><i>↗</i></button>}
